import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Sample Delhi public toilets data with realistic coordinates
const delhiToilets = [
  {
    name: "Connaught Place Public Toilet",
    description: "Clean public toilet near Palika Bazaar",
    latitude: 28.6328,
    longitude: 77.2197,
    address: "Palika Bazaar, Connaught Place, New Delhi",
    area: "Connaught Place",
    city: "Delhi",
    state: "Delhi",
    pincode: "110001",
    isFree: true,
    isPaid: false,
    isMale: true,
    isFemale: true,
    isUnisex: false,
    isWheelchairAccessible: true,
    hasBabyChangingStation: false,
    hasShower: false,
    isOpen24_7: true,
    isVerified: true,
    isActive: true,
    cleanlinessRating: 4.2,
    safetyRating: 4.5,
    overallRating: 4.3,
    currentCrowdLevel: 2,
    hasWater: true,
    hasTissue: true,
    smellLevel: 1,
    openingTime: "06:00",
    closingTime: "22:00",
    lastCleanedAt: new Date("2024-05-11T08:00:00Z"),
    cleaningFrequency: "daily",
    contactNumber: "+91-11-23456789",
    locationType: "public",
  },
  {
    name: "Rajiv Chowk Metro Station Toilet",
    description: "Metro station toilet facility",
    latitude: 28.6330,
    longitude: 77.2167,
    address: "Rajiv Chowk Metro Station, New Delhi",
    area: "Connaught Place",
    city: "Delhi",
    state: "Delhi",
    pincode: "110001",
    isFree: false,
    isPaid: true,
    price: 5.0,
    isMale: true,
    isFemale: true,
    isUnisex: false,
    isWheelchairAccessible: true,
    hasBabyChangingStation: false,
    hasShower: false,
    isOpen24_7: false,
    isVerified: true,
    isActive: true,
    cleanlinessRating: 3.8,
    safetyRating: 4.7,
    overallRating: 4.1,
    currentCrowdLevel: 3,
    hasWater: true,
    hasTissue: true,
    smellLevel: 2,
    openingTime: "06:00",
    closingTime: "23:00",
    lastCleanedAt: new Date("2024-05-11T10:00:00Z"),
    cleaningFrequency: "twice_daily",
    contactNumber: "+91-11-23456789",
    locationType: "metro",
  },
  {
    name: "Select Citywalk Mall Toilet",
    description: "Premium mall toilet facility",
    latitude: 28.5706,
    longitude: 77.1979,
    address: "Select Citywalk, Saket, New Delhi",
    area: "Saket",
    city: "Delhi",
    state: "Delhi",
    pincode: "110017",
    isFree: true,
    isPaid: false,
    isMale: true,
    isFemale: true,
    isUnisex: true,
    isWheelchairAccessible: true,
    hasBabyChangingStation: true,
    hasShower: false,
    isOpen24_7: false,
    isVerified: true,
    isActive: true,
    cleanlinessRating: 4.7,
    safetyRating: 4.8,
    overallRating: 4.6,
    currentCrowdLevel: 2,
    hasWater: true,
    hasTissue: true,
    smellLevel: 0,
    openingTime: "10:00",
    closingTime: "22:00",
    lastCleanedAt: new Date("2024-05-11T09:00:00Z"),
    cleaningFrequency: "hourly",
    contactNumber: "+91-11-40809000",
    locationType: "mall",
  },
  {
    name: "AIIMS Hospital Public Toilet",
    description: "Hospital toilet facility",
    latitude: 28.5665,
    longitude: 77.2090,
    address: "AIIMS, Ansari Nagar, New Delhi",
    area: "AIIMS",
    city: "Delhi",
    state: "Delhi",
    pincode: "110029",
    isFree: true,
    isPaid: false,
    isMale: true,
    isFemale: true,
    isUnisex: true,
    isWheelchairAccessible: true,
    hasBabyChangingStation: true,
    hasShower: false,
    isOpen24_7: true,
    isVerified: true,
    isActive: true,
    cleanlinessRating: 3.5,
    safetyRating: 4.2,
    overallRating: 3.8,
    currentCrowdLevel: 4,
    hasWater: true,
    hasTissue: false,
    smellLevel: 3,
    openingTime: "00:00",
    closingTime: "23:59",
    lastCleanedAt: new Date("2024-05-11T07:00:00Z"),
    cleaningFrequency: "daily",
    contactNumber: "+91-11-26588500",
    locationType: "hospital",
  },
  {
    name: "India Gate Public Toilet",
    description: "Public toilet near India Gate",
    latitude: 28.6107,
    longitude: 77.2295,
    address: "India Gate, New Delhi",
    area: "India Gate",
    city: "Delhi",
    state: "Delhi",
    pincode: "110001",
    isFree: true,
    isPaid: false,
    isMale: true,
    isFemale: true,
    isUnisex: false,
    isWheelchairAccessible: false,
    hasBabyChangingStation: false,
    hasShower: false,
    isOpen24_7: true,
    isVerified: true,
    isActive: true,
    cleanlinessRating: 3.2,
    safetyRating: 3.8,
    overallRating: 3.4,
    currentCrowdLevel: 3,
    hasWater: true,
    hasTissue: false,
    smellLevel: 3,
    openingTime: "06:00",
    closingTime: "22:00",
    lastCleanedAt: new Date("2024-05-11T06:00:00Z"),
    cleaningFrequency: "daily",
    contactNumber: "+91-11-23456789",
    locationType: "public",
  },
  {
    name: "Khan Market Toilet",
    description: "Market area toilet facility",
    latitude: 28.6029,
    longitude: 77.2301,
    address: "Khan Market, New Delhi",
    area: "Khan Market",
    city: "Delhi",
    state: "Delhi",
    pincode: "110003",
    isFree: false,
    isPaid: true,
    price: 10.0,
    isMale: true,
    isFemale: true,
    isUnisex: false,
    isWheelchairAccessible: false,
    hasBabyChangingStation: false,
    hasShower: false,
    isOpen24_7: false,
    isVerified: true,
    isActive: true,
    cleanlinessRating: 4.0,
    safetyRating: 4.3,
    overallRating: 4.1,
    currentCrowdLevel: 2,
    hasWater: true,
    hasTissue: true,
    smellLevel: 1,
    openingTime: "09:00",
    closingTime: "20:00",
    lastCleanedAt: new Date("2024-05-11T08:30:00Z"),
    cleaningFrequency: "twice_daily",
    contactNumber: "+91-11-24675187",
    locationType: "market",
  },
  {
    name: "Lajpat Nagar Market Toilet",
    description: "Busy market toilet facility",
    latitude: 28.5672,
    longitude: 77.2433,
    address: "Lajpat Nagar Market, New Delhi",
    area: "Lajpat Nagar",
    city: "Delhi",
    state: "Delhi",
    pincode: "110024",
    isFree: false,
    isPaid: true,
    price: 5.0,
    isMale: true,
    isFemale: true,
    isUnisex: false,
    isWheelchairAccessible: false,
    hasBabyChangingStation: false,
    hasShower: false,
    isOpen24_7: false,
    isVerified: true,
    isActive: true,
    cleanlinessRating: 2.8,
    safetyRating: 3.5,
    overallRating: 3.1,
    currentCrowdLevel: 4,
    hasWater: true,
    hasTissue: false,
    smellLevel: 4,
    openingTime: "08:00",
    closingTime: "21:00",
    lastCleanedAt: new Date("2024-05-11T07:00:00Z"),
    cleaningFrequency: "daily",
    contactNumber: "+91-11-29812345",
    locationType: "market",
  },
  {
    name: "Hauz Khas Village Toilet",
    description: "Trendy area toilet facility",
    latitude: 28.5512,
    longitude: 77.1935,
    address: "Hauz Khas Village, New Delhi",
    area: "Hauz Khas",
    city: "Delhi",
    state: "Delhi",
    pincode: "110016",
    isFree: false,
    isPaid: true,
    price: 10.0,
    isMale: true,
    isFemale: true,
    isUnisex: true,
    isWheelchairAccessible: false,
    hasBabyChangingStation: false,
    hasShower: false,
    isOpen24_7: false,
    isVerified: true,
    isActive: true,
    cleanlinessRating: 3.9,
    safetyRating: 4.1,
    overallRating: 4.0,
    currentCrowdLevel: 3,
    hasWater: true,
    hasTissue: true,
    smellLevel: 2,
    openingTime: "11:00",
    closingTime: "23:00",
    lastCleanedAt: new Date("2024-05-11T11:00:00Z"),
    cleaningFrequency: "twice_daily",
    contactNumber: "+91-11-26543210",
    locationType: "market",
  },
  {
    name: "Dhaula Kuan Petrol Pump Toilet",
    description: "Petrol pump toilet facility",
    latitude: 28.6094,
    longitude: 77.1667,
    address: "Dhaula Kuan Petrol Pump, New Delhi",
    area: "Dhaula Kuan",
    city: "Delhi",
    state: "Delhi",
    pincode: "110010",
    isFree: true,
    isPaid: false,
    isMale: true,
    isFemale: true,
    isUnisex: false,
    isWheelchairAccessible: false,
    hasBabyChangingStation: false,
    hasShower: false,
    isOpen24_7: true,
    isVerified: true,
    isActive: true,
    cleanlinessRating: 3.3,
    safetyRating: 3.9,
    overallRating: 3.5,
    currentCrowdLevel: 1,
    hasWater: true,
    hasTissue: false,
    smellLevel: 2,
    openingTime: "00:00",
    closingTime: "23:59",
    lastCleanedAt: new Date("2024-05-11T05:00:00Z"),
    cleaningFrequency: "daily",
    contactNumber: "+91-11-24103456",
    locationType: "petrol_pump",
  },
  {
    name: "Sarojini Nagar Market Toilet",
    description: "Popular market toilet facility",
    latitude: 28.5711,
    longitude: 77.2041,
    address: "Sarojini Nagar Market, New Delhi",
    area: "Sarojini Nagar",
    city: "Delhi",
    state: "Delhi",
    pincode: "110023",
    isFree: false,
    isPaid: true,
    price: 5.0,
    isMale: true,
    isFemale: true,
    isUnisex: false,
    isWheelchairAccessible: false,
    hasBabyChangingStation: false,
    hasShower: false,
    isOpen24_7: false,
    isVerified: true,
    isActive: true,
    cleanlinessRating: 2.9,
    safetyRating: 3.4,
    overallRating: 3.1,
    currentCrowdLevel: 5,
    hasWater: true,
    hasTissue: false,
    smellLevel: 4,
    openingTime: "10:00",
    closingTime: "20:00",
    lastCleanedAt: new Date("2024-05-11T06:30:00Z"),
    cleaningFrequency: "daily",
    contactNumber: "+91-11-24675432",
    locationType: "market",
  }
];

// Sample badges
const badges = [
  {
    name: "First Review",
    description: "Write your first toilet review",
    icon: "🌟",
    pointsRequired: 10,
    category: "reviewer"
  },
  {
    name: "Explorer",
    description: "Visit 10 different toilets",
    icon: "🗺️",
    pointsRequired: 50,
    category: "explorer"
  },
  {
    name: "Helper",
    description: "Report 5 issues that get resolved",
    icon: "🤝",
    pointsRequired: 30,
    category: "helper"
  },
  {
    name: "Photographer",
    description: "Upload 20 toilet photos",
    icon: "📸",
    pointsRequired: 40,
    category: "contributor"
  },
  {
    name: "Trustworthy",
    description: "Get 50 helpful votes on your reviews",
    icon: "✅",
    pointsRequired: 100,
    category: "trusted"
  }
];

async function seedData() {
  try {
    console.log("Starting database seeding...");

    // Clear existing data
    await prisma.review.deleteMany();
    await prisma.report.deleteMany();
    await prisma.imageUpload.deleteMany();
    await prisma.checkIn.deleteMany();
    await prisma.userBadge.deleteMany();
    await prisma.badge.deleteMany();
    await prisma.toilet.deleteMany();
    await prisma.user.deleteMany();

    console.log("Cleared existing data");

    // Create badges
    for (const badge of badges) {
      await prisma.badge.create({
        data: badge
      });
    }
    console.log("Created badges");

    // Create toilets
    for (const toilet of delhiToilets) {
      await prisma.toilet.create({
        data: toilet
      });
    }
    console.log("Created toilets");

    console.log("Database seeding completed successfully!");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedData();
